name: ANGEL
description: "Angel benchmark"
tags: [static, link-based]

execution:
  cwd: baselines/ANGEL
  entrypoint: [docker-compose, run, angel, --angel]
  containerized: true

parameters:
  threshold: 0.4
  min_comsize: 3

datasets:
  star-wars:
    parameters:
      min_comsize: 5