name: ARCHANGEL
description: "Archangel benchmark"
tags: [dynamic, link-based]

execution:
  cwd: baselines/ANGEL
  entrypoint: [docker-compose, run, angel]
  containerized: true

parameters:
  threshold: 0.4
  min_comsize: 3

datasets:
  star-wars:
    parameters:
      min_comsize: 5