database: com-youtube
description: ''
name: com-youtube
tags: [static, ground-truth]
versions:
  static:
    parameters: {}
    type: edgelist_static
  static_small:
    parameters:
      subsample: 0.5
    type: edgelist_static
