database: DBLP-HCN
description: ''
name: DBLP-HCN
tags: [dynamic, ground-truth]
versions:
  static:
    parameters: { }
    type: edgelist_static
  split_5:
    type: edgelist_snapshots
    parameters:
      snapshot_count: 5
      snapshot_coverage: 0.95

