database: DBLP-HCN
description: ''
name: DBLP-HCN
tags:
- dynamic
- ground-truth
- overlapping
versions:
  split_5:
    parameters:
      snapshot_count: 5
      snapshot_coverage: 0.95
    partless: false
    type: edgelist_snapshots
  static:
    parameters: {}
    partless: false
    type: edgelist_static
