database: DBLP-V1
description: ''
name: DBLP-V1
tags: [dynamic]
versions:
  static:
    parameters: { }
    type: edgelist_static
  split_5:
    type: edgelist_snapshots
    parameters:
      snapshot_count: 5
      snapshot_coverage: 0.95

