database: enron-mail-20150507
description: ''
name: enron-mail-20150507
tags: [dynamic, interaction]
versions:
  split_10_small:
    type: edgelist_snapshots
    parameters:
      subsample: 0.5
      snapshot_count: 10
      snapshot_coverage: 0.95
  split_5:
    type: edgelist_snapshots
    parameters:
      snapshot_count: 5
      snapshot_coverage: 0.95
  split_10:
    type: edgelist_snapshots
    parameters:
      snapshot_count: 10
      snapshot_coverage: 0.95
  split_20:
    type: edgelist_snapshots
    parameters:
      snapshot_count: 20
      snapshot_coverage: 0.95

