database: imdb-5000-movie-dataset
description: ''
name: imdb-5000-movie-dataset
tags:
- dynamic
versions:
  split_5:
    parameters:
      snapshot_count: 5
      snapshot_coverage: 0.95
    partless: false
    type: edgelist_snapshots
  static:
    parameters: {}
    partless: false
    type: edgelist_static
