database: social-distancing-student
description: ''
name: social-distancing-student
tags:
- dynamic
versions:
  split_10:
    parameters:
      snapshot_count: 10
      snapshot_coverage: 0.95
    partless: false
    type: edgelist_snapshots
  split_5:
    parameters:
      snapshot_count: 5
      snapshot_coverage: 0.95
    partless: false
    type: edgelist_snapshots
  static:
    parameters: {}
    partless: false
    type: edgelist_static
