database: star-wars
description: ''
name: star-wars
tags: [dynamic]
versions:
  split_5:
    type: snapshots
    parameters:
      snapshot_count: 5
      snapshot_coverage: 0.95
  static:
    type: static
    parameters: {}
