database: sx-superuser
description: ''
name: sx-superuser
tags: [dynamic, interaction]
versions:
  split_6:
    type: edgelist_snapshots
    parameters:
      snapshot_count: 6
      snapshot_coverage: 0.95
  split_10:
    type: edgelist_snapshots
    parameters:
      snapshot_count: 10
      snapshot_coverage: 0.95

