database: synthetic-rdyn
description: ''
name: synthetic-rdyn
tags: [dynamic, ground-truth, synthetic]
versions:
  small_5:
    parameters:
      method: 'rdyn'
      seed: 1337
      size: 400
      snapshots: 6
    type: edgelist_snapshots
