database: synthetic-rdyn
description: ''
name: synthetic-rdyn
tags: [dynamic, ground-truth, synthetic]
versions:
  small_5_a:
    parameters:
      method: 'rdyn'
      seed: 1337
      size: 400
      snapshots: 5
      alpha: 2.5
      new_node: 0.15
      del_node: 0.1
      avg_deg: 10
      sigma: 0.6
    type: edgelist_snapshots
  small_5_b:
    parameters:
      method: 'rdyn'
      seed: 1337
      size: 400
      snapshots: 5
      alpha: 2.5
      new_node: 0.15
      del_node: 0.1
      avg_deg: 15
      sigma: 0.6
    type: edgelist_snapshots
  small_5_c:
    parameters:
      method: 'rdyn'
      seed: 1337
      size: 400
      snapshots: 5
      alpha: 2.5
      new_node: 0.15
      del_node: 0.1
      avg_deg: 20
      sigma: 0.6
    type: edgelist_snapshots
  small_5_aa:
    parameters:
      method: 'rdyn'
      seed: 1337
      size: 400
      snapshots: 5
      alpha: 3.5
      new_node: 0.15
      del_node: 0.1
      avg_deg: 10
      sigma: 0.6
    type: edgelist_snapshots
  small_5_bb:
    parameters:
      method: 'rdyn'
      seed: 1337
      size: 400
      snapshots: 5
      alpha: 3.5
      new_node: 0.15
      del_node: 0.1
      avg_deg: 15
      sigma: 0.6
    type: edgelist_snapshots
  small_5_cc:
    parameters:
      method: 'rdyn'
      seed: 1337
      size: 400
      snapshots: 5
      alpha: 3.5
      new_node: 0.15
      del_node: 0.1
      avg_deg: 20
      sigma: 0.6
    type: edgelist_snapshots
