type: paper
title: "Community Detection through Representation learning in Evolving Heterogenous Networks"
subtitle: "A Master’s Thesis proposal"
authors:
  name: "Egor Dmitriev"
  email: "e.dmitriev@students.uu.nl"
  affiliation:
    institution: "Utrecht University"
    country: "The Netherlands"
topic: "dynamic networks, community detection"
bibliography: ../../refs.bib
toc: true
abstract: |
  | Recent developments in big data and graph representation learning have allowed researchers to make breakthroughs in social network analysis and the identification of communities. While opening a lot of research opportunities, such approaches are highly limited to snapshots of rapidly evolving social networks. This, in fact, is a great simplification of the real-world situation which is always evolving and expanding by the user and/or machine interactions.
  |
  | Relying on novel research of dynamic graph representation learning, the goal of my thesis project is to build a framework for community detection and representation in dynamic heterogeneous networks. To verify the merit of the proposed framework, it will be evaluated against baselines on static heterogeneous graphs, and analyzed against gathered twitter dataset on covid measures.
toc-depth: 2
xnos-capitalise: true
