name: ANGEL
description: "Angel benchmark"
tags: [ static, link-based, overlapping ]

execution:
  cwd: baselines/ANGEL
  entrypoint: [ docker-compose, run, angel, --angel ]
  containerized: true

parameters:
  run_count: 5
  timeout: 600
  threshold:
    min: 0.001
    max: 0.9
  min_comsize: 1


datasets:
  com-youtube:
    versions: [ ]
    parameters: { }
  DBLP-HCN:
    versions: [ ]
    #      - static
    parameters: { }
  DBLP-V1:
    versions: [ ]
    #      - static
    parameters: { }
  DBLP-V3:
    versions: [ ]
    parameters: { }
  email-Eu-core:
    versions:
      - static
    parameters: { }
  house-of-representatives-congress-116:
    versions:
      - static_small
    parameters: { }
  imdb-5000-movie-dataset:
    versions:
      - static
    parameters: { }
  misc-football:
    versions:
      - static
    parameters: { }
  social-distancing-student:
    versions: [ ]
    #      - static
    parameters: { }
  star-wars:
    versions:
      - static
    parameters: { }
  ucidata-zachary:
    versions:
      - static
    parameters: { }