name: ComE
description: "ComE benchmark"
tags: [static, representation-based]

execution:
  cwd: baselines/ComE
  entrypoint: [docker-compose, run, come]
  containerized: true

parameters:
  run_count: 5
  timeout: -1
  number_walks:
    values: [5, 15, 30]
  walk_length:
    values: [40, 80]
  representation_size:
    values: [32, 64, 128]
  num_workers: 10
  num_iter:
    values: [10, 20, 50, 80]
  reg_covar: 0.00001
  batch_size: 50
  window_size:
    values: [5, 10, 20, 40]
  negative: 5
  lr:
    min: 0.001
    max: 0.2
#    default: 0.025
  alpha:
    min: 0.1
    max: 0.2
  beta:
    min: 0.1
    max: 0.2
  down_sampling: 0.0
  ks: 5
#  table_size: 100000000
  table_size:
    values: [10000, 100000]
  k:
    values: [3, 5, 10, 20, 40]

datasets:
  com-youtube:
    versions: []
    parameters: {}
  DBLP-HCN:
    versions:
      - static
    parameters: {}
  DBLP-V1:
    versions: []
    parameters: { }
  DBLP-V3:
    versions: []
    parameters: { }
  email-Eu-core:
    versions:
      - static
    parameters: { }
  house-of-representatives-congress-116:
    versions:
      - static_small
    parameters: { }
  imdb-5000-movie-dataset:
    versions:
      - static
    parameters: { }
  misc-football:
    versions:
      - static
    parameters: { }
  social-distancing-student:
    versions: []
    parameters: { }
  star-wars:
    versions:
      - static
    parameters: { }
  ucidata-zachary:
    versions:
      - static
    parameters: { }