name: CommunityGAN
description: "CommunityGAN"
tags: [static, representation-based, overlapping]

execution:
  cwd: baselines/CommunityGAN
  entrypoint: [docker-compose, run, communitygan]
  containerized: true

parameters:
  run_count: 15
  timeout: 600
  n_communities: -1
  min_communities: 5
  max_communities: 500
  n_trials: 10
  alpha:
    min: 0.05
    max: 0.2
  beta:
    min: 0.05
    max: 0.2
  allow_reference: 0
  disable_eta: 1
  same_eta: 1
  max_iter: 500
  save_iter: 5000
  sample_iter: 10
  zero_threshold: 0.0001
  remain_largest: 0
  # Traning Settings
  motif_size: 3
  batch_size_gen: 64
  batch_size_dis: 64
  n_sample_gen: 5
  n_sample_dis: 5
  lr_gen: 1e-3
    min: 1e-3
    max: 1e-2
  lr_dis:
    min: 1e-3
    max: 1e-2
  n_epochs: 10
    values: [10]
  n_epochs_gen: 3
  n_epochs_dis: 3
  gen_interval: 3
  dis_interval: 3
  update_ratio: 1
  max_value: 1000
  # Model saving
  load_model: True
  save_steps: 10
  # Hyper params
  n_emb:
    values: [32, 64, 128]
  num_threads: 16
  window_size:
    values: [5, 10, 15]
  overlap_threshold: 1.0

datasets:
  com-youtube:
    versions: []
    parameters: {}
  DBLP-HCN:
    versions:
      - static
    parameters: {}
  DBLP-V1:
    versions:
      - static
    parameters: { }
  DBLP-V3:
    versions: []
    parameters: { }
  email-Eu-core:
    versions:
      - static
    parameters: { }
  imdb-5000-movie-dataset:
    versions:
      - static
    parameters: { }
  misc-football:
    versions:
      - static
    parameters: { }
  social-distancing-student:
    versions:
      - static
    parameters: { }
  star-wars:
    versions:
      - static
    parameters: { }
  ucidata-zachary:
    versions:
      - static
    parameters: { }