name: GEMSEC
description: "GEMSEC benchmark"
tags: [static, link-based]

execution:
  cwd: baselines/KarateClub
  entrypoint: [docker-compose, run, karateclub, GEMSEC]
  containerized: true

parameters:
  run_count: 5
  timeout: 3600
  walk_number:
    values: [5, 10]
  walk_length:
    values: [40, 80]
  dimensions: 32
  negative_samples: 5
  window_size:
    values: [5, 10]
  learning_rate:
    min: 0.05
    max: 0.2
  clusters:
    values: [3, 4, 8, 16, 32]
  gamma:
    min: 0.05
    max: 0.2
  seed: 42

datasets:
  com-youtube:
    versions: []
    parameters: {}
  DBLP-HCN:
    versions: []
#      - static
    parameters: {}
  DBLP-V1:
    versions: []
    parameters: { }
  DBLP-V3:
    versions: []
    parameters: { }
  email-Eu-core:
    versions:
      - static
    parameters: { }
  house-of-representatives-congress-116:
    versions:
      - static_small
    parameters: { }
  imdb-5000-movie-dataset:
    versions:
      - static
    parameters: { }
  misc-football:
    versions:
      - static
    parameters: { }
  social-distancing-student:
    versions: []
    parameters: { }
  star-wars:
    versions:
      - static
    parameters: { }
  ucidata-zachary:
    versions:
      - static
    parameters: { }