name: GreeneDCD-louvain
description: "GreeneDCD benchmark"
tags: [dynamic, link-based]

execution:
  cwd: baselines/GreeneDCD
  entrypoint: [docker-compose, run, greenedcd, louvain, --dynamic]
  containerized: true

parameters:
  weighted: false
  epsilon: 0.001
  reuse_partition: false
  level: -1
  matching_threshold: 0.1
  death:
    values: [3, 4]
  persist_threshold: 1
  min_length: 2
  max_step: -1

datasets:
  com-youtube:
    versions: []
    parameters: {}
  DBLP-HCN:
    versions:
      - split_5
    parameters: {}
  DBLP-V1:
    versions:
      - split_5_small
      - split_5
      - split_10
    parameters: { }
  DBLP-V3:
    versions:
      - split_5
      - split_10
    parameters: { }
  email-Eu-core:
    versions: []
    parameters: { }
  enron-mail-20150507:
    versions:
      - split_10_small
      - split_5
      - split_10
      - split_20
    parameters: { }
  imdb-5000-movie-dataset:
    versions:
      - split_5
    parameters: { }
  misc-football:
    versions: []
    parameters: { }
  social-distancing-student:
    versions:
      - split_5
      - split_10
    parameters: { }
  star-wars:
    versions:
      - split_5
      - split_7
    parameters: { }
  sx-mathoverflow:
    versions:
      - split_6
      - split_10
    parameters: { }
  sx-superuser:
    versions:
      - split_6
      - split_10
    parameters: { }
  ucidata-zachary:
    versions: []
    parameters: { }