name: GreeneDCD-MOSES
description: "GreeneDCD benchmark"
tags: [dynamic, link-based, overlapping]

execution:
  cwd: baselines/GreeneDCD
  entrypoint: [docker-compose, run, greenedcd, moses, --dynamic]
  containerized: true

parameters:
  matching_threshold: 0.1
  death:
    values: [3, 4]
  persist_threshold: 1
  min_length: 2
  max_step: -1

datasets:
  star-wars:
    versions:
      - snapshots_k=5
    parameters:
      max_step: -1
